### ISSUE TITLE
Too much distortion

### ISSUE THREAD

**Issue by MichjuX** [Flaton1/walkie-talkie-mod#12]
While talking throght walkie talkie there's too much distortion. It makes talking impossible. Maybe add option to config to switch that.

**Comment by Flaton1** [comment]
On which version and platform is the distortion significant?

**Comment by MichjuX** [comment]
On [FABRIC] Walkie-Talkie 1.19.2-1.2.0

Using voicechat-fabric-1.19.2-2.4.8

**Comment by Flaton1** [comment]
The voice filter will be removed for version 1.2.1 to be released on 06/14/23
