### ISSUE TITLE
You can't hear others through the walkie talkie.

### ISSUE THREAD

**Issue by TonySokachu** [Flaton1/walkie-talkie-mod#23]
**Describe the bug**
Can't hear other

**Expected behavior**
I would expect other's voice when holding the walkie talkie in hand, although i could not hear them while both using an wt. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser chrome
 - Version: idk wtf

**Additional context**
The speakers are working properly, tho the wt doesn't

**Comment by Flaton1** [comment]
Bug fixed in 1.2.2
