### ISSUE TITLE
Voice filter in walkie-talkie - Can't hear what my friends say

### ISSUE THREAD

**Issue by ghost** [Flaton1/walkie-talkie-mod#24]
Version: 1.2.0
Minecraft: 1.16.5

There's a voice filter on the walkie-talkie that doesn't let me hear what my friends say, and neither can my friends hear me. The speaker works fine, the issue is just with the walkie-talkies.
Can this be added to the config file, so there's a way to turn it off?

**Comment by Flaton1** [comment]
Bug fixed in 1.2.2

**Comment by ghost** [comment]
And where the 1.2.2 version is available to download?
