### ISSUE TITLE
Changing the voice filter to he clearer

### ISSUE THREAD

**Issue by edgywavymanonmc** [Flaton1/walkie-talkie-mod#26]
**Is your feature request related to a problem? Please describe.**
The voice filter for the walkie talkies is far too garbled and full of static to be intelligible.

**Describe the solution you'd like**
I'd like for the voice filter to be changed to be clearer so that it's easier to hear and understand what the other person is saying.

**Describe alternatives you've considered**
Maybe make the voice filter clearer with each upgrade so you have even more incentive to get all the way up to netherite, obviously with that being the highest upgrade.

**Additional context**
Add any other context or screenshots about the feature request here. No

**Comment by Flaton1** [comment]
Bug fixed in 1.2.2
