### ISSUE TITLE
speakers not working

### ISSUE THREAD

**Issue by MinecraftedGaming** [Flaton1/walkie-talkie-mod#28]
**Describe the bug**
cant get speakers to work on 1.19.2 forge server

**To Reproduce**
1. add mod to server
2. get radios (iron) and turn them
3. make speaker and turn it on
4. watch as the speaker doesnt do anything

**Expected behavior**
speaker play audio of people talking on that channel

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser its a server... on minecraft..
 - Version 1.19.2

**Smartphone (please complete the following information):**
 - its a minecraft mod... how the fuck am i going to use a smartphone

**Additional context**
tried with multiple players no response

**Comment by Flaton1** [comment]
I'm sorry, there will be no more updates for 1.19.3.

**Comment by Flaton1** [comment]
Hello, I tried to reproduce the bug, but everything works fine. But the bug may come from a certain version of simple voice chat or another mod. I'll be able to help you if you give me more information: logs, mod list, version of simple voice chat.

**Comment by MinecraftedGaming** [comment]
heres a complete list of mods/versions on my server

https://drive.google.com/drive/u/0/folders/1HgQDqnwMVlIynwaC33nUaQd512JnzbPD?ths=true

**Comment by MinecraftedGaming** [comment]
did he die or something... i need to get this fixed

**Comment by Flaton1** [comment]
Using the same modpack I have no problem. The bug may come from a bad configuration.

**Comment by MinecraftedGaming** [comment]
i never touched the config till today but the issue was present from the first run with the mod

**Comment by MinecraftedGaming** [comment]
had to remove the mod due to extreme lag when multiple players are trying to use radios. this issue its due to low end server so that might be cause of the original issue.
