### ISSUE TITLE
Push-to-talk function limited to walkie talkies

### ISSUE THREAD

**Issue by MochidsukiC** [Flaton1/walkie-talkie-mod#29]
Apart from normal Voice Chat,
I would like to have a setting that allows walkie-talkie to be voice detected or select push-to-talk, and a key binding that is different from the basic Simple Voice Chat.

**Comment by TheVeggum** [comment]
The way me and my friend got around this limitation was by using Plasmovoice for our proximity voice chat with continuous streaming, and putting Simple Voice Chat to push to talk and only using it for radios. Plasmo also has some great addons like the ability for sculk sensors to detect if you're talking like there is for SVC.
