### ISSUE TITLE
Problems with the walkie-talkie

### ISSUE THREAD

**Issue by FireWolfFW** [Flaton1/walkie-talkie-mod#30]
For some reason, there is no sound from walkie-talkies, there is no feedback
In general, I can't hear my friends, but the speaker works as it should

Game version 1.16.5
switching to another version is NOT POSSIBLE

**Comment by TonySokachu** [comment]
I have the same problem. There are more people playing 1.16.5 than are playing 1.19(+above) You should consider updating it.
