### ISSUE TITLE
Walkie-Talkie works cross-dimension

### ISSUE THREAD

**Issue by jonko0493** [Flaton1/walkie-talkie-mod#31]
**Describe the bug**
The walkie-talkie shouldn't, imo, work between the overworld and the nether. But, when you have players close enough in terms of world coordinates but in different dimensions, it does function.

**To Reproduce**
1. Give each player a diamond walkie-talkie.
2. Have one player go into the nether.
3. Observe that they can talk to each other.

**Expected behavior**
No voice packets should be transmitted when in different dimensions.

**Client (please complete the following information):**
 - OS: Windows
 - Simple Voice Chat Version: 2.4.27
 - Minecraft Version: 1.20.1
 - Mod Version: 1.2.2

**Server (please complete the following information, if you own the server):**
 - OS: Ubuntu
 - Simple Voice Chat Version: 2.4.27
 - Minecraft Version: 1.20.1
 - Mod Version: 1.2.2

**Comment by Flaton1** [comment]
Fix for 1.2.3
